MyExercise/Models/ExerciseRecord.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MyExercise.Models
{
    public class ExerciseRecord
    {
        [Key]
        public long Id { get; set; }
        [Required, MaxLength(100)]
        [Display(Name = "Exercise Name")]
        public string ExerciseName { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Exercise Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? ExerciseDate { get; set; }
        [Required]
        [Range(1, 120)]
        [Display(Name = "Duration In Minutes")]
        public int DurationInMinutes { get; set; }
        public DateTime CreationDate { get; set; }
    }
}

MyExercise/Models/ViewModels/ExerciseVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList.Mvc;

namespace MyExercise.Models.ViewModels
{
    public class ExerciseVM
    {
        public ExerciseVM() { }
        public ExerciseRecord ExerciseRecord { get; set; }
        public IQueryable<ExerciseRecord> ExerciseRecords { get; set; }
        public PagedList.IPagedList<ExerciseRecord> ExePagedList { get; set; }
    }
}

MyExercise/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyExercise.Models;
using MyExercise.Models.ViewModels;
using MyExercise.Repository;
using PagedList;


namespace MyExercise.Controllers
{
    public class ExerciseController : Controller
    {

        private IExerciseRepository<ExerciseRecord> exeRepository = null;
        //public ExerciseController()
        //{
        //    this.exeRepository = new ExerciseRepository<ExerciseRecord>();
        //}
        // dependency injection
        public ExerciseController(ExerciseRepository<ExerciseRecord> exeRepository)
        {
            this.exeRepository = exeRepository;
        }

        // GET: Exercise
        public ActionResult Index(string thisFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = thisFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var exercises = from emp in exeRepository.GetAllData()
                            select emp;
            // IQueryable query = from x in appEntities
            //var sql = ((System.Data.Objects.ObjectQuery)exercises).ToTraceString();
            //var sql = ((System.Data.Entity.Core.Objects.ObjectQuery)exercises).ToTraceString();
            //Console.WriteLine(">>>> show sql " + sql);
            //var exercises = exeRepository.GetAllData().ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                exercises = exercises.Where(emp => emp.ExerciseName.ToUpper().Contains(searchString.ToUpper()));
            }

            exercises = exercises.OrderByDescending(x => x.CreationDate);
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var exePagedList = exercises.ToPagedList(pageNumber, pageSize);
            var exercisesVM = new ExerciseVM();
            exercisesVM.ExePagedList = exePagedList;
            return View(exercisesVM);
        }

        [HttpPost]
        [HandleError]
        public ActionResult Index(ExerciseRecord exerciseRecord, string thisFilter, string searchString, int? page)
        {
            try
            {
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = thisFilter;
                }

                ViewBag.CurrentFilter = searchString;
                var exercises = from emp in exeRepository.GetAllData()
                                select emp;
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(exerciseRecord.ExerciseName))
                    {
                        ModelState.AddModelError("", "Name is required");
                    }
                    if (exerciseRecord.ExerciseDate == DateTime.MinValue)
                    {
                        ModelState.AddModelError("", "Exercise Date is invalid");
                    }
                    if (exerciseRecord.DurationInMinutes < 1 || exerciseRecord.DurationInMinutes > 120)
                    {
                        ModelState.AddModelError("", "Duration In Minutes is out of the range (1-120)");
                    }

                    ExerciseRecord exerciseFound = exercises.FirstOrDefault(x => x.ExerciseName == exerciseRecord.ExerciseName
                                                                              && x.CreationDate == DateTime.Today);
                    if (exerciseFound == null)
                    {
                        exerciseRecord.CreationDate = DateTime.Now;
                        exeRepository.InsertRecord(exerciseRecord);
                        exeRepository.SaveRecord();
                        ViewBag.Message = "Sucess";
                        ModelState.Clear();
                        return Json(new { result = "OK" });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Fail: " + exerciseRecord.ExerciseName + " is already in the system today.");
                    }
                }
                //Response.StatusCode = 400;
                exercises = exercises.OrderByDescending(x => x.CreationDate);
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                
                var exePagedList = exercises.ToPagedList(pageNumber, pageSize);
                var exercisesVM = new ExerciseVM();
                exercisesVM.ExePagedList = exePagedList;
                exercisesVM.ExerciseRecord = exerciseRecord;
                return PartialView("~/Views/Exercise/_CreateExe.cshtml", exercisesVM);
            } catch (Exception ex) {
                throw ex;
            }
        }


    }
}

MyExercise/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyExercise.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyExercise/Views/Exercise/Index.cshtml
@model MyExercise.Models.ViewModels.ExerciseVM
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //var pagedlist = (PagedList.IPagedList)Model;
    var pagedlist = (PagedList.IPagedList)Model.ExePagedList;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@*<form id="searchform">
    <p>
        Exercise Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
</form>*@
<div id="searchTar">
    <h2>Competition 1</h2>
    @using (Ajax.BeginForm("Index", "Exercise", new AjaxOptions()
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET",
        UpdateTargetId = "searchTar"
    }))
    {
        <p>
            Exercise Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }

    <button type="button" class="btn btn-primary btn-default" data-toggle="modal" data-target="#myModal1">
        Create Exercise
    </button>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExerciseRecord.ExerciseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExerciseRecord.ExerciseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExerciseRecord.DurationInMinutes)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.ExePagedList)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ExerciseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExerciseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DurationInMinutes)
                </td>

                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>*@
            </tr>
        }

    </table>

    <div class="panel-footer">
        Page @(pagedlist.PageCount < pagedlist.PageNumber ? 0 : pagedlist.PageNumber) of @pagedlist.PageCount


        @Html.PagedListPager(pagedlist, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
</div> <!-- searchTar -->
@using (Ajax.BeginForm("Index", "Exercise", new AjaxOptions()
                                                        {
                                                            HttpMethod = "POST"
                                                            ,UpdateTargetId = "myModalBodyDiv1"
                                                            ,OnSuccess = "OnSuccess"
                                                        }
                                                        , new { id = "myForm" }
                                                        ))

{
    <div class="modal fade" id="myModal1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3 class="modal-title">Create Exercise</h3>
                </div>
                <div class="modal-body" id="myModalBodyDiv1">
                    @Html.Partial("_CreateExe")
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" id="btn-cancel" class="btn btn-default" type="button" >Cancel</button>
                    <button class="btn btn-success" id="btn-submit" type="submit">
                        Submit
                    </button>
                </div>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/exercise/exercise.js"></script>

MyExercise/Views/Exercise/Save.cshtml
@model MyExercise.Models.ExerciseRecord

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Save", "Exercise", FormMethod.Post, new { id = "popupForm" }))
{

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model.ExerciseName, new { @class = "col-lg-3 col-sm-3 control-label" })
    <div class="col-lg-6">
        @Html.EditorFor(model => model.ExerciseName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ExerciseName, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.ExerciseDate, new { @class = "col-lg-3 col-sm-3 control-label" })
    <div class="col-lg-6">
        @Html.EditorFor(model => model.ExerciseDate, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ExerciseDate, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.DurationInMinutes, new { @class = "col-lg-3 col-sm-3 control-label" })
    <div class="col-lg-6">
        @Html.EditorFor(model => model.DurationInMinutes, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.DurationInMinutes, "", new { @class = "text-danger" })

    </div>
</div>

<div>
    <input type="submit" value="Save" onclick="Popupform()" /> //then it could call the global function variable Popupform
</div>
}

MyExercise/Views/Exercise/_CreateExe.cshtml
@model MyExercise.Models.ViewModels.ExerciseVM

@{
    ViewBag.Title = "Create";
}

@if (ViewBag.Message != null)
{
    <span class="text-success">@ViewBag.Message</span>
}

<span class="alert-danger">
    @Html.ValidationSummary()
</span>
<div class="form-horizontal">
    <!-- Modal -->
        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseRecord.ExerciseName, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ExerciseRecord.ExerciseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExerciseRecord.ExerciseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseRecord.ExerciseDate, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ExerciseRecord.ExerciseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExerciseRecord.ExerciseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseRecord.DurationInMinutes, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ExerciseRecord.DurationInMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExerciseRecord.DurationInMinutes, "", new { @class = "text-danger" })
            </div>
        </div>
</div>

MyExercise/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyExercise/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyExercise/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MyExercise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>